AllCops:
  Exclude:
    - metadata.rb
    - "**/metadata.rb"
    - Vagrantfile
    - Thorfile
    - Berksfile
    - vendor/**/*
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 27
Metrics/AbcSize:
  Max: 36
